<?php
/**
 * Created D/13/08/2017
 * Updated S/29/04/2023
 *
 * Copyright 2015-2023 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * Copyright 2015-2016 | Fabrice Creuzot <fabrice.creuzot~label-park~com>
 * Copyright 2017-2018 | Fabrice Creuzot <fabrice~reactive-web~fr>
 * Copyright 2020-2023 | Fabrice Creuzot <fabrice~cellublue~com>
 * https://github.com/luigifab/openmage-maillog
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$help    = $this->helper('maillog');
$element = $this->getData('element');
$config  = $this->getData('config');
$types   = $this->getData('types');

$titleFirst   = $help->escapeEntities($this->__('Emails content and attachments'), true);
$titleSecond  = $help->escapeEntities($this->__('All emails data'), true);
$titleBgColor = $help->escapeEntities($this->__('Background color'), true);
$titleTtColor = $help->escapeEntities($this->__('Text color'), true);

$textReset   = $this->__('Reset');
$textDefault = $this->__('Default');

$textTimes = [];
for ($i = 1; $i <= 18; $i++) {
	if ($i == 1)
		$textTimes[$i] = $this->__('%d month', $i);  // 1
	else if ($i <= 4)
		$textTimes[$i] = $help->_('%d months', $i);  // 2-4
	else
		$textTimes[$i] = $this->__('%d months', $i); // 5+
}
for ($i = 2 * 12; $i <= 8 * 12; $i += 12) {
	$j = $i / 12;
	if ($j <= 4)
		$textTimes[$i] = $help->_('%d years', $j);  // 2-4
	else
		$textTimes[$i] = $this->__('%d years', $j); // 5+
}

$bgColor = Mage::getStoreConfig('maillog/general/default_bgcolor');
$ttColor = Mage::getStoreConfig('maillog/general/default_ttcolor');
?>

<tr id="row_<?php echo $element->getHtmlId() ?>_head">
	<td class="label" colspan="2">
		<?php echo $element->getLabel() ?>
	</td>
	<td class="scope-label">
		<?php echo $element->getScopeLabel() // global ?>
	</td>
	<td></td>
	<?php if (!empty($element->getPath())): // PR 2774 ?>
		<td></td>
	<?php endif ?>
</tr>
<tr id="row_<?php echo $element->getHtmlId() ?>">
	<td colspan="<?php echo empty($element->getPath()) ? 4 : 5 // PR 2774 ?>">
		<ul id="lifetimeConfig">
			<?php foreach ($types as $type): ?>
				<li>
					<span title="<?php echo $type ?>"><?php echo ($type == 'all') ? $this->__('<b>all</b>') : $type ?></span>

					<?php $key = str_replace(' ', '_', $type).'_data' ?>
					<select name="groups[general][fields][special_config][value][<?php echo $key ?>]" title="<?php echo $titleFirst ?>">
						<?php if (empty($config[$key]) || ($config[$key] == '--')): ?>
							<option selected="selected">--</option>
						<?php else: ?>
							<option>--</option>
						<?php endif ?>
						<?php for ($i = 1; $i <= 18; $i++): ?>
							<?php if (!empty($config[$key]) && ($config[$key] == $i)): ?>
								<option value="<?php echo $i ?>" selected="selected"><?php echo $textTimes[$i] ?></option>
							<?php else: ?>
								<option value="<?php echo $i ?>"><?php echo $textTimes[$i] ?></option>
							<?php endif ?>
						<?php endfor ?>
						<?php for ($i = 2 * 12; $i <= 8 * 12; $i += 12): ?>
							<?php if (!empty($config[$key]) && ($config[$key] == $i)): ?>
								<option value="<?php echo $i ?>" selected="selected"><?php echo $textTimes[$i] ?></option>
							<?php else: ?>
								<option value="<?php echo $i ?>"><?php echo $textTimes[$i] ?></option>
							<?php endif ?>
						<?php endfor ?>
					</select>

					<?php $key = str_replace(' ', '_', $type).'_all' ?>
					<select name="groups[general][fields][special_config][value][<?php echo $key ?>]" title="<?php echo $titleSecond ?>">
						<?php if (empty($config[$key]) || ($config[$key] == '--')): ?>
							<option selected="selected">--</option>
						<?php else: ?>
							<option>--</option>
						<?php endif ?>
						<?php for ($i = 1; $i <= 18; $i++): ?>
							<?php if (!empty($config[$key]) && ($config[$key] == $i)): ?>
								<option value="<?php echo $i ?>" selected="selected"><?php echo $textTimes[$i] ?></option>
							<?php else: ?>
								<option value="<?php echo $i ?>"><?php echo $textTimes[$i] ?></option>
							<?php endif ?>
						<?php endfor ?>
						<?php for ($i = 2 * 12; $i <= 8 * 12; $i += 12): ?>
							<?php if (!empty($config[$key]) && ($config[$key] == $i)): ?>
								<option value="<?php echo $i ?>" selected="selected"><?php echo $textTimes[$i] ?></option>
							<?php else: ?>
								<option value="<?php echo $i ?>"><?php echo $textTimes[$i] ?></option>
							<?php endif ?>
						<?php endfor ?>
					</select>

					<?php $key = str_replace(' ', '_', $type) ?>
					<input type="text" name="groups[general][fields][special_config][value][<?php echo $key ?>_back_color]"
						value="<?php echo empty($config[$key.'_back_color']) ? $bgColor : $config[$key.'_back_color'] ?>"
						title="<?php echo $titleBgColor ?>"
						class="color {hash:true} input-text" />
					<input type="text" name="groups[general][fields][special_config][value][<?php echo $key ?>_text_color]"
						value="<?php echo empty($config[$key.'_text_color']) ? $ttColor : $config[$key.'_text_color'] ?>"
						title="<?php echo $titleTtColor ?>"
						class="color {hash:true} input-text" />

					<button type="button" class="slink reset" onclick="maillog.resetValues(this);">
						<?php echo $textReset //$this->__('Reset') ?>
					</button>
					<button type="button" class="slink default" onclick="maillog.defaultLifetime(this, '<?php echo $bgColor ?>', '<?php echo $ttColor ?>');">
						<?php echo $textDefault //$this->__('Default') ?>
					</button>

					<?php if (!empty($canDelete)): ?>
						<input type="hidden" name="groups[general][fields][special_config][value][<?php echo $key ?>_delete]" value="0" />
						<button type="button" class="slink" onclick="maillog.removeLifetime(this);">
							<?php echo empty($textDelete) ? $textDelete = $this->__('Delete') : $textDelete ?>
						</button>
					<?php endif ?>
					<?php if ($type == 'all') { $canDelete = true; } // tout ce qui est après all est supprimable ?>
				</li>
			<?php endforeach ?>
		</ul>
	</td>
</tr>