<?php
/**
 * Created D/13/08/2017
 * Updated V/12/02/2021
 *
 * Copyright 2015-2021 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * Copyright 2015-2016 | Fabrice Creuzot <fabrice.creuzot~label-park~com>
 * Copyright 2017-2018 | Fabrice Creuzot <fabrice~reactive-web~fr>
 * Copyright 2020-2021 | Fabrice Creuzot <fabrice~cellublue~com>
 * https://www.luigifab.fr/openmage/maillog
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$help   = $this->helper('maillog');
$config = $this->getConfig();
$types  = $this->getTypes();

$titleFirst   = $help->escapeEntities($this->__('Emails content and attachments'), true);
$titleSecond  = $help->escapeEntities($this->__('All emails data'), true);
$titleBgColor = $help->escapeEntities($this->__('Background color'), true);
$titleTtColor = $help->escapeEntities($this->__('Text color'), true);

$model   = Mage::getSingleton('maillog/email');
$bgColor = $model->getDefaultBgColor();
$ttColor = $model->getDefaultTxtColor();
?>

<tr id="<?php echo $this->getHtmlId() ?>_head">
	<td class="label" colspan="2"><?php echo $this->getLabel() ?></td>
	<td class="scope-label"><?php echo $this->getScopeLabel() ?></td>
	<td></td>
</tr>
<tr id="<?php echo $this->getHtmlId() ?>">
	<td colspan="4">
		<ul id="lifetimeConfig">
			<?php foreach ($types as $type):
				if ($type == '--')
					continue;
			?>
				<li>
					<span>
						<?php echo in_array($type, ['without', 'all']) ? $this->__('<b>'.$type.'</b>') : $type ?>
						<?php //echo $this->__('<b>without</b>') pour le translate.php ?>
						<?php //echo $this->__('<b>all</b>')     pour le translate.php ?>
					</span>

					<?php $key = str_replace(' ', '_', $type).'_data' ?>
					<select name="groups[general][fields][special_config][value][<?php echo $key ?>]" title="<?php echo $titleFirst ?>">
						<option>--</option>
						<?php for ($i = 2; $i <= 12; $i++): ?>
							<?php if (!empty($config[$key]) && ($config[$key] == $i)): ?>
								<option value="<?php echo $i ?>" selected="selected">
									<?php echo ($i <= 4) ? $help->_('%d months', $i) : $this->__('%d months', $i) // 2-4 ou 5+ ?>
								</option>
							<?php else: ?>
								<option value="<?php echo $i ?>">
									<?php echo ($i <= 4) ? $help->_('%d months', $i) : $this->__('%d months', $i) // 2-4 ou 5+ ?>
								</option>
							<?php endif ?>
						<?php endfor ?>
						<?php for ($i = 2 * 12; $i <= 8 * 12; $i += 12): $j = $i / 12; ?>
							<?php if (!empty($config[$key]) && ($config[$key] == $i)): ?>
								<option value="<?php echo $i ?>" selected="selected">
									<?php echo ($j <= 4) ? $help->_('%d years', $j) : $this->__('%d years', $j) // 2-4 ou 5+ ?>
								</option>
							<?php else: ?>
								<option value="<?php echo $i ?>">
									<?php echo ($j <= 4) ? $help->_('%d years', $j) : $this->__('%d years', $j) // 2-4 ou 5+ ?>
								</option>
							<?php endif ?>
						<?php endfor ?>
					</select>

					<?php $key = str_replace(' ', '_', $type).'_all' ?>
					<select name="groups[general][fields][special_config][value][<?php echo $key ?>]" title="<?php echo $titleSecond ?>">
						<option>--</option>
						<?php for ($i = 2; $i <= 12; $i++): ?>
							<?php if (!empty($config[$key]) && ($config[$key] == $i)): ?>
								<option value="<?php echo $i ?>" selected="selected">
									<?php echo ($i <= 4) ? $help->_('%d months', $i) : $this->__('%d months', $i) // 2-4 ou 5+ ?>
								</option>
							<?php else: ?>
								<option value="<?php echo $i ?>">
									<?php echo ($i <= 4) ? $help->_('%d months', $i) : $this->__('%d months', $i) // 2-4 ou 5+ ?>
								</option>
							<?php endif ?>
						<?php endfor ?>
						<?php for ($i = 2 * 12; $i <= 8 * 12; $i += 12): $j = $i / 12; ?>
							<?php if (!empty($config[$key]) && ($config[$key] == $i)): ?>
								<option value="<?php echo $i ?>" selected="selected">
									<?php echo ($j <= 4) ? $help->_('%d years', $j) : $this->__('%d years', $j) // 2-4 ou 5+ ?>
								</option>
							<?php else: ?>
								<option value="<?php echo $i ?>">
									<?php echo ($j <= 4) ? $help->_('%d years', $j) : $this->__('%d years', $j) // 2-4 ou 5+ ?>
								</option>
							<?php endif ?>
						<?php endfor ?>
					</select>

					<?php $key = str_replace(' ', '_', $type) ?>
					<input type="color" name="groups[general][fields][special_config][value][<?php echo $key ?>_back_color]"
						value="<?php echo mb_strtolower(empty($config[$key.'_back_color']) ? $bgColor : $config[$key.'_back_color']) ?>"
						title="<?php echo $titleBgColor ?>" />
					<input type="color" name="groups[general][fields][special_config][value][<?php echo $key ?>_text_color]"
						value="<?php echo mb_strtolower(empty($config[$key.'_text_color']) ? $ttColor : $config[$key.'_text_color']) ?>"
						title="<?php echo $titleTtColor ?>" />

					<button type="button" class="slink" onclick="maillog.resetLifetime(this, '<?php echo $bgColor ?>');">
						<?php echo $this->__('Reset') ?>
					</button>

					<?php if (!empty($canDelete)): ?>
						<input type="hidden" name="groups[general][fields][special_config][value][<?php echo $key ?>_delete]" value="0" />
						<button type="button" class="slink" onclick="maillog.removeLifetime(this);">
							<?php echo $this->__('Delete') ?>
						</button>
					<?php endif ?>
					<?php if ($type == 'all') { $canDelete = true; } // tout ce qui est après all est supprimable ?>
				</li>
			<?php endforeach ?>
		</ul>
	</td>
</tr>