<?php
/**
 * Created M/28/09/2021
 * Updated V/08/10/2021
 *
 * Copyright 2015-2021 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * Copyright 2015-2016 | Fabrice Creuzot <fabrice.creuzot~label-park~com>
 * Copyright 2017-2018 | Fabrice Creuzot <fabrice~reactive-web~fr>
 * Copyright 2020-2021 | Fabrice Creuzot <fabrice~cellublue~com>
 * https://www.luigifab.fr/openmage/maillog
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$config = $this->getData('config');
?>

</tbody>
</table>

<table class="form-list" cellspacing="0">
<tr id="<?php echo $this->getHtmlId() ?>">
	<td class="label" colspan="2">
		<table cellspacing="0" class="data border mauticrating">
			<tr>
				<th>Rating</th>
				<th>Recency<br />(days since last order)<br /><em>rating_order_recency</em></th>
				<th>Frequency<br />(total orders placed)<br /><em>rating_order_frequency</em></th>
				<th>Monetary<br />(total money spent, global currency)<br /><em>rating_order_monetary</em></th>
			</tr>
			<tr>
				<th>5</th>
				<td>
					<label>
						from 0 to
						<input type="number"
							name="groups[mautic][fields][mautic_config][value][5a]" value="<?php echo $config['5a'] ?? '' ?>"
							min="0" step="1" class="input-text validate-greater-than-zero" />
					</label>
				</td>
				<td>
					more than below
					<input type="number" style="visibility:hidden;" />
				</td>
				<td>
					more than below
					<input type="number" style="visibility:hidden;" />
				</td>
			</tr>
			<?php foreach (range(4, 2) as $idx): ?>
				<tr>
					<th><?php echo $idx ?></th>
					<td>
						<label>
							from above to
							<input type="number"
								name="groups[mautic][fields][mautic_config][value][<?php echo $idx ?>a]" value="<?php echo $config[$idx.'a'] ?? '' ?>"
								min="0" step="1" class="input-text validate-greater-than-zero" />
						</label>
					</td>
					<td>
						<label>
							from below to
							<input type="number"
								name="groups[mautic][fields][mautic_config][value][<?php echo $idx ?>b]" value="<?php echo $config[$idx.'b'] ?? '' ?>"
								min="0" step="1" class="input-text validate-greater-than-zero" />
						</label>
					</td>
					<td>
						<label>
							from below to
							<input type="number"
								name="groups[mautic][fields][mautic_config][value][<?php echo $idx ?>c]" value="<?php echo $config[$idx.'c'] ?? '' ?>"
								min="0" step="1" class="input-text validate-greater-than-zero" />
						</label>
					</td>
				</tr>
			<?php endforeach ?>
			<tr>
				<th>1</th>
				<td>
					more than above
					<input type="number" style="visibility:hidden;" />
				</td>
				<td>
					<label>
						from 0 to
						<input type="number"
							name="groups[mautic][fields][mautic_config][value][1b]" value="<?php echo $config['1b'] ?? '' ?>"
							min="0" step="1" class="input-text validate-greater-than-zero" />
					</label>
				</td>
				<td>
					<label>
						from 0 to
						<input type="number"
							name="groups[mautic][fields][mautic_config][value][1c]" value="<?php echo $config['1c'] ?? '' ?>"
							min="0" step="1" class="input-text validate-greater-than-zero" />
					</label>
				</td>
			</tr>
		</table>
	</td>
	<td class="scope-label"><?php echo $this->getScopeLabel() ?></td>
	<td></td>
</tr>