<?php
/**
 * Created J/09/05/2019
 * Updated M/28/12/2021
 *
 * Copyright 2015-2022 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * Copyright 2015-2016 | Fabrice Creuzot <fabrice.creuzot~label-park~com>
 * Copyright 2017-2018 | Fabrice Creuzot <fabrice~reactive-web~fr>
 * Copyright 2020-2022 | Fabrice Creuzot <fabrice~cellublue~com>
 * https://www.luigifab.fr/openmage/maillog
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$help   = $this->helper('maillog');
$config = $this->getData('config');

$titleCode = $help->escapeEntities($this->__('Code'));
$titleDesc = $help->escapeEntities($this->__('Description'));
?>

<tr id="<?php echo $this->getHtmlId() ?>" class="grid">
	<td colspan="4">
		<table cellspacing="0" class="data border data-table" id="pictureConfig">
			<thead>
				<tr class="headings">
					<th style="width:20em;"><?php echo $this->__('Code') ?> / <?php echo $this->__('Description') ?></th>
					<th><?php echo $this->__('Breakpoint / Size (<em>width</em> x <em>height</em>) / Ratio') ?></th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<td colspan="2">
						<button type="button" class="scalable add" onclick="maillog.addPicture(this);">
							<span><?php echo $this->__('Add') ?></span>
						</button>
					</td>
				</tr>
			</tfoot>
			<tbody>
				<tr class="template" data-next="<?php echo empty($config) ? 0 : (max(array_keys($config)) + 1) ?>">
					<td>
						<label>
							<input type="text" placeholder="<?php echo $titleCode ?>"
								name="groups[general][fields][special_config][value][IIDDXX][c]"
								class="input-text cde required-entry validate-alphanum" />
						</label>
						<label>
							<input type="text" placeholder="<?php echo $titleDesc ?>"
								name="groups[general][fields][special_config][value][IIDDXX][d]"
								class="input-text cmt" />
						</label>
						<br />
						<button type="button" class="slink" onclick="maillog.deletePicture(this);">
							<?php echo $this->__('Delete') ?>
						</button>
					</td>
					<td class="config">
						<ul>
							<li class="line default">
								<div class="bp">
									default
								</div>
								<div class="sz">
									<label title="width (px)">
										<input type="number"
											name="groups[general][fields][special_config][value][IIDDXX][0][w]"
											min="0" step="1" class="input-text required-entry validate-greater-than-zero" />
									</label>
									x
									<label title="height (px)">
										<input type="number"
											name="groups[general][fields][special_config][value][IIDDXX][0][h]"
											min="0" step="1" class="input-text required-entry validate-greater-than-zero" />
									</label>
								</div>
							</li>
							<li class="line breakpoint">
								<div class="bp">
									max-width:
									<label title="max-width (px)">
										<input type="number"
											name="groups[general][fields][special_config][value][IIDDXX][KKEEYY][b]"
											min="0" step="1" class="input-text required-entry validate-greater-than-zero" />
									</label>
								</div>
								<div class="sz">
									<label title="width (px)">
										<input type="number"
											name="groups[general][fields][special_config][value][IIDDXX][KKEEYY][w]"
											min="0" step="1" class="input-text required-entry validate-greater-than-zero" />
									</label>
									x
									<label title="height (px)">
										<input type="number"
											name="groups[general][fields][special_config][value][IIDDXX][KKEEYY][h]"
											min="0" step="1" class="input-text required-entry validate-greater-than-zero" />
									</label>
								</div>
								<div class="rt"></div>
								<div class="btn">
									<button type="button" class="slink" onclick="maillog.deleteBreak(this);">
										<?php echo $this->__('Delete') ?>
									</button>
								</div>
							</li>
						</ul>
						<div class="line">
							<div class="bp"></div>
							<div class="sz"></div>
							<div class="rt"></div>
							<div class="btn">
								<button type="button" class="slink" onclick="maillog.addBreak(this, IIDDXX);">
									<?php echo $this->__('Add') ?>
								</button>
							</div>
						</div>
					</td>
				</tr>
				<?php foreach ($config as $idx => $data): ?>
					<tr class="config">
						<td>
							<label>
								<input type="text" placeholder="<?php echo $titleCode ?>"
									name="groups[general][fields][special_config][value][<?php echo $idx ?>][c]"
									value="<?php echo $data['c'] ?>"
									class="input-text cde required-entry validate-alphanum" />
							</label>
							<label>
								<input type="text" placeholder="<?php echo $titleDesc ?>"
									name="groups[general][fields][special_config][value][<?php echo $idx ?>][d]"
									value="<?php echo str_replace("\n", ' ', $help->escapeEntities($data['d'], true)) ?>"
									class="input-text cmt" />
							</label>
							<br />
							<button type="button" class="slink" onclick="maillog.deletePicture(this);">
								<?php echo $this->__('Delete') ?>
							</button>
						</td>
						<td class="config">
							<ul>
								<li class="line default">
									<div class="bp">
										default
									</div>
									<div class="sz">
										<label title="width (px)">
											<input type="number"
												name="groups[general][fields][special_config][value][<?php echo $idx ?>][0][w]"
												min="0" step="1" value="<?php echo $data[0]['w'] ?>"
												class="input-text required-entry validate-greater-than-zero" />
										</label>
										x
										<label title="height (px)">
											<input type="number"
												name="groups[general][fields][special_config][value][<?php echo $idx ?>][0][h]"
												min="0" step="1" value="<?php echo $data[0]['h'] ?>"
												class="input-text required-entry validate-greater-than-zero" />
										</label>
									</div>
									<div class="rt">
										<?php echo $help->getNumber($data[0]['w'] / $data[0]['h'], ['precision' => 2]) ?>
									</div>
								</li>
								<?php foreach ($data as $key => $subdata): ?>
									<?php if (!is_numeric($key) || !is_array($subdata) || empty($key)) continue; ?>
									<li class="line breakpoint">
										<div class="bp">
											max-width:
											<label title="max-width (px)">
												<input type="number"
													name="groups[general][fields][special_config][value][<?php echo $idx ?>][<?php echo $key ?>][b]"
													min="0" step="1" value="<?php echo $subdata['b'] ?>"
													class="input-text required-entry validate-greater-than-zero" />
											</label>
										</div>
										<div class="sz">
											<label title="width (px)">
												<input type="number"
													name="groups[general][fields][special_config][value][<?php echo $idx ?>][<?php echo $key ?>][w]"
													min="0" step="1" value="<?php echo $subdata['w'] ?>"
													class="input-text required-entry validate-greater-than-zero" />
											</label>
											x
											<label title="height (px)">
												<input type="number"
													name="groups[general][fields][special_config][value][<?php echo $idx ?>][<?php echo $key ?>][h]"
													min="0" step="1" value="<?php echo $subdata['h'] ?>"
													class="input-text required-entry validate-greater-than-zero" />
											</label>
										</div>
										<div class="rt">
											<?php echo $help->getNumber($subdata['w'] / $subdata['h'], ['precision' => 2]) ?>
										</div>
										<div class="btn">
											<button type="button" class="slink" onclick="maillog.deleteBreak(this);">
												<?php echo $this->__('Delete') ?>
											</button>
										</div>
									</li>
								<?php endforeach ?>
							</ul>
							<div class="line">
								<div class="bp"></div>
								<div class="sz"></div>
								<div class="rt"></div>
								<div class="btn">
									<button type="button" class="slink" onclick="maillog.addBreak(this, <?php echo $idx ?>);">
										<?php echo $this->__('Add') ?>
									</button>
								</div>
							</div>
						</td>
					</tr>
				<?php endforeach ?>
			</tbody>
		</table>
		<code class="maillogexamples">
			      {{picture code="..." file="..." attribute="..." helper="..."}}
			<br />Mage::helper('maillog/picture')->getTag(['code' => '...', 'file' => '...', 'attribute' => '...', 'helper' => '...']);
			<br />
			<br /><em style="text-decoration:underline;">for a product image (default helper is catalog/image and default attribute is image)</em>
			<br />{{picture code="..." file="/x/y/xyz.xyz" id="example"}}
			<br />{{picture code="..." file="/x/y/xyz.xyz" attribute="small_image" id="example"}}
			<br />{{picture code="..." product="id|sku" id="example"}}
			<br />{{picture code="..." product="id|sku" attribute="small_image" id="example"}}
			<?php if ($this->helper('core')->isModuleEnabled('Luigifab_Apijs')): ?>
				<br /><em style="text-decoration:underline;">for a category image (default helper is catalog/image)</em>
				<br />{{picture code="..." file="xyz.xyz" attribute="category" id="example"}}
				<br />{{picture code="..." category="id" id="example"}}
				<br /><em style="text-decoration:underline;">for a wysiwyg image (default helper is catalog/image)</em>
				<br />{{picture code="..." file="wysiwyg/xyz.xyz" attribute="wysiwyg" id="example"}}
			<?php endif ?>
		</code>
	</td>
</tr>
<?php // debug ?>
<?php if (!empty($this->getRequest()->getParam('test'))): ?>
	<tr>
		<td colspan="4">
			<pre style="padding:0.5em; white-space:pre-wrap; background-color:beige;">
<b>[ product file ]</b>
<?php echo str_replace(['picture', Mage::getBaseUrl('media'), '605003.jpg'], ['<b>picture</b>', '.../', '<b>605003.jpg</b>'], htmlspecialchars(
	Mage::getModel('varien/filter_template')->filter('{{picture code="test" alt="Multiple word\'s" file="/6/0/605003.jpg"}}')
)) ?>


<b>[ category file ]</b>
<?php echo str_replace(['picture', Mage::getBaseUrl('media'), '605003.jpg'], ['<b>picture</b>', '.../', '<b>605003.jpg</b>'], htmlspecialchars(
	Mage::getModel('varien/filter_template')->filter('{{picture code="test" alt="Multiple word\'s" attribute="category" file="605003.jpg"}}')
)) ?>


<b>[ wysiwyg file ]</b>
<?php echo str_replace(['picture', Mage::getBaseUrl('media'), '605003.jpg'], ['<b>picture</b>', '.../', '<b>605003.jpg</b>'], htmlspecialchars(
	Mage::getModel('varien/filter_template')->filter('{{picture code="test" alt="Multiple word\'s" attribute="wysiwyg" file="wysiwyg/abc/605003.jpg"}}')
)) ?>


<b>[ product 2 ]</b>
<?php echo str_replace(['picture', Mage::getBaseUrl('media'), '605003.jpg'], ['<b>picture</b>', '.../', '<b>605003.jpg</b>'], htmlspecialchars(
	$this->helper('maillog/picture')->getTag(['code' => 'test', 'product' => 2])
)) ?>


<b>[ category 6 ]</b>
<?php echo str_replace(['picture', Mage::getBaseUrl('media'), '605003.jpg'], ['<b>picture</b>', '.../', '<b>605003.jpg</b>'], htmlspecialchars(
	$this->helper('maillog/picture')->getTag(['code' => 'test', 'category' => 6])
)) ?></pre>
		</td>
	</tr>
<?php endif ?>