<?php
/**
 * Created L/18/01/2021
 * Updated M/28/09/2021
 *
 * Copyright 2015-2021 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * Copyright 2015-2016 | Fabrice Creuzot <fabrice.creuzot~label-park~com>
 * Copyright 2017-2018 | Fabrice Creuzot <fabrice~reactive-web~fr>
 * Copyright 2020-2021 | Fabrice Creuzot <fabrice~cellublue~com>
 * https://www.luigifab.fr/openmage/maillog
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$help  = $this->helper('maillog');
$email = $this->getData('email');
[$bgColor, $ttColor] = $this->getData('colors');

?><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="mul">
<head>
	<title><?php echo $subject = $email->getSubject() ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="robots" content="noindex,nofollow">
	<link rel="icon" type="image/x-icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>">
	<?php echo $this->getData('mail_head') ?>
	<style type="text/css">
	body { margin:0 !important; padding:0 2rem 2rem !important; width:auto !important; height:auto !important; overflow-y:scroll !important; }
	body > ul.attachments {
		display:flex; justify-content:center; margin:0 -2rem 2.4em;
		list-style:none; font-size:0.7rem; color:<?php echo $ttColor ?>; background-color:<?php echo $bgColor ?>;
	}
	body > ul.attachments li {
		display:flex; flex-direction:column; justify-content:center;
		margin:1em 0; line-height:142%;
	}
	body > ul.attachments li:first-child {
		padding:0 4em 0 58px; min-height:60px;
		background:url("<?php echo $this->getSkinUrl('images/luigifab/maillog/humanity-mail.svg') ?>") no-repeat left center;
	}
	body > ul.attachments li select { padding:5px; font-size:0.7rem; border:1px solid gray; background:transparent; }
	body > ul.attachments li a { text-decoration:underline; color:<?php echo $ttColor ?>; }
	body > ul.attachments li a[type] {
		display:flex; flex-direction:column; justify-content:center; padding:0 1.7em 0 50px; min-height:60px;
		text-decoration:none; cursor:pointer; background-repeat:no-repeat; background-position:left center;
	}
	body > ul.attachments li a[type] {
		background-image:url("<?php echo $this->getSkinUrl('images/luigifab/maillog/humanity-file.svg') ?>");
	}
	body > ul.attachments li a[type="application/pdf"] {
		background-image:url("<?php echo $this->getSkinUrl('images/luigifab/maillog/humanity-pdf.svg') ?>");
	}
	body > p.emailold { margin:6em; text-align:center; font-size:13px; color:#E41101; }
	body > pre { margin:1em; white-space:pre-wrap; }
	@media print {
		body > ul.attachments { font-size:0.6rem; }
		body > ul.attachments span.print { display:none; }
		body > ul.attachments li:first-child a { text-decoration:none; }
	}
	</style>
</head>
<body>
	<?php if (!empty($subject)): ?>
		<ul class="attachments">
			<li>
				<?php if (!empty(Mage::registry('maillog_preview')) && !empty($name = $this->getRequest()->getParam('file'))):
					$base    = $this->helper('core/url')->getCurrentUrl();
					$current = Mage::app()->getStore()->getId();
					$stores  = Mage::getResourceModel('core/store_collection')->addFieldToFilter('is_active', 1)->setOrder('store_id', 'asc');
					$langs   = array_reduce(
						glob(BP.'/app/locale/*/template/email/'.preg_replace('#[^\w/-]#', '', $name).'.html'),
						static function ($names, $name) {
							$name = mb_substr($name, mb_strpos($name, '/locale/') + 8, 5);
							$names[$name] = $name;
							return $names;
						},
						[]);
				?>
					<label>
						<select lang="mul" onchange="self.location.href = this.value;">
							<optgroup label="Usage by store view">
								<?php foreach ($stores as $id => $store):
									$lang = Mage::getStoreConfig('general/locale/code', $id);
								?>
									<?php if (in_array($lang, $langs)):
										$url = preg_replace('#/store/\d+/#', '/store/'.$id.'/', $base);
										unset($langs[$lang]);
									?>
										<?php if ($current == $id): ?>
											<option value="<?php echo $url ?>" selected="selected">
												<?php echo $id ?> / <?php echo $store->getData('name') ?> / <?php echo $lang ?>
											</option>
										<?php else: ?>
											<option value="<?php echo $url ?>">
												<?php echo $id ?> / <?php echo $store->getData('name') ?> / <?php echo $lang ?>
											</option>
										<?php endif ?>
									<?php endif ?>
								<?php endforeach ?>
							</optgroup>
							<?php if (!empty($langs)): ?>
								<optgroup label="Not used">
									<?php $current = Mage::getStoreConfig('general/locale/code', $current) ?>
									<?php foreach ($langs as $lang): ?>
										<?php if ($current == $lang): ?>
											<option disabled="disabled" selected="selected"><?php echo $lang ?></option>
										<?php else: ?>
											<option disabled="disabled"><?php echo $lang ?></option>
										<?php endif ?>
									<?php endforeach ?>
								</optgroup>
							<?php endif ?>
						</select>
					</label>
				<?php else: ?>
					<strong class="subject"><?php echo $this->__('Subject: %s', $subject) ?></strong>
					<?php if (!in_array($email->getData('sent_at'), ['', '0000-00-00 00:00:00', null])): ?>
						<span><?php echo $this->__('Sent At: %s', Mage::getSingleton('core/locale')->date($email->getData('sent_at'))->toString(Zend_Date::DATETIME_FULL)) ?></span>
					<?php endif ?>
					<?php if (!empty($sender = $email->getData('mail_sender'))): ?>
						<span><?php echo $this->__('Sender: %s', $help->getHumanEmailAddress($sender)) ?></span>
					<?php endif ?>
					<span><?php echo $this->__('<a %s>Print</a> this email only if necessary.', 'href="javascript:self.print();"') ?></span>
				<?php endif ?>
			</li>
			<?php foreach ($email->getEmailParts() as $key => $part):
				$size = rtrim(chunk_split(str_replace("\n", '', $part->getContent())));
				$size = $help->getNumberToHumanSize(mb_strlen(base64_decode($size)));
			 ?>
				<li>
					<a href="<?php echo $email->getEmbedUrl('download', ['_secure' => Mage::app()->getStore()->isCurrentlySecure(), 'part' => $key]) ?>" type="<?php echo $part->type ?>">
						<strong><?php echo $part->filename ?></strong>
						<span><?php echo $size ?></span>
					</a>
				</li>
			<?php endforeach ?>
		</ul>
	<?php endif ?>
	<?php if (empty($email->getData('deleted'))): ?>
		<?php echo $this->getData('mail_body') ?>
	<?php else: ?>
		<p class="emailold"><?php echo $this->__('Sorry, your email is too old, it is not available online anymore.') ?></p>
	<?php endif ?>
</body>
</html>