<?php
/**
 * Created S/14/11/2015
 * Updated M/08/11/2016
 *
 * Copyright 2015-2017 | Fabrice Creuzot <fabrice.creuzot~label-park~com>, Fabrice Creuzot (luigifab) <code~luigifab~info>
 * https://redmine.luigifab.info/projects/magento/wiki/maillog
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$customer = Mage::registry('current_customer');
?>

<?php if (Mage::getStoreConfigFlag('maillog/general/enabled') && is_object($customer)): ?>
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-customer-view"><?php echo $this->__('Transactionnal emails - %s', $customer->getEmail()) ?></h4>
		</div>
		<fieldset>
			<?php
				$stats = Mage::getResourceModel('maillog/email_collection');
				$stats->getSelect()->reset(Zend_Db_Select::COLUMNS)->columns(array('status')); // optimisation maximale
				$stats->addFieldToFilter('mail_recipients', array('like' => '%'.$customer->getEmail().'%'));

				$isBounce = Mage::getModel('maillog/bounce')->load($customer->getEmail())->isBounce();
				$isSubscribed = Mage::getModel('newsletter/subscriber')->loadByCustomer($customer)->isSubscribed();
			?>
			<?php if (Mage::getStoreConfigFlag('maillog/bounce/enabled')): ?>
				<p><?php echo ($isBounce) ? '<strong>'.$this->__('Email address does not exist!').'</strong>' : $this->__('Email address is valid.') ?>
				<br /><?php echo $this->__('%d email(s), %d send, %d open/read.',
					$stats->getSize(),
					count($stats->getItemsByColumnValue('status', 'sent')) + count($stats->getItemsByColumnValue('status', 'read')),
					count($stats->getItemsByColumnValue('status', 'read'))
				) ?></p>
				<?php if (!$isBounce && $isSubscribed): ?>
					<p><?php echo $this->__('Customer is subscribed to the newsletter.') ?></p>
				<?php endif ?>
			<?php else: ?>
				<p><?php echo $this->__('%d email(s), %d send, %d open/read.',
					$stats->getSize(),
					count($stats->getItemsByColumnValue('status', 'sent')) + count($stats->getItemsByColumnValue('status', 'read')),
					count($stats->getItemsByColumnValue('status', 'read'))
				) ?></p>
				<?php if ($isSubscribed): ?>
					<p><?php echo $this->__('Customer is subscribed to the newsletter.') ?></p>
				<?php endif ?>
			<?php endif ?>
		</fieldset>
	</div>
<?php endif ?>