<?php
/**
 * Created V/27/04/2018
 * Updated M/15/01/2019
 *
 * Copyright 2015-2019 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * Copyright 2015-2016 | Fabrice Creuzot <fabrice.creuzot~label-park~com>
 * Copyright 2017-2018 | Fabrice Creuzot <fabrice~reactive-web~fr>
 * https://www.luigifab.fr/magento/maillog
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$name = $this->getName();
$options = $this->getOptions();
?>

<tr>
	<td class="label">
		<label for="maillog_sync_mapping_customerid_field"><?php echo $this->__('Customer Id field') ?></label>
	</td>
	<td class="value">
		<select lang="mul" class="select" id="maillog_sync_mapping_customerid_field" name="groups[sync][fields][mapping_customerid_field][value]">
			<option value="">--</option>
			<?php foreach ($options['field'] as $option): ?>
				<?php if (!empty($option['selected'])): ?>
					<option value="<?php echo $option['value'] ?>" selected="selected" class="has">
						<?php echo !empty($option['label']) ? $option['label'].' ('.$option['value'].')' : $option['value'] ?>
					</option>
				<?php else: ?>
					<option value="<?php echo $option['value'] ?>">
						<?php echo !empty($option['label']) ? $option['label'].' ('.$option['value'].')' : $option['value'] ?>
					</option>
				<?php endif ?>
			<?php endforeach ?>
		</select>
		<p class="note"><span><?php echo $this->__('In case of a change of email address, the customer identification in the system will be done with the customer id.') ?></span></p>
	</td>
	<td class="scope-label">
		<?php echo $this->__('[GLOBAL]') ?>
	</td>
	<td></td>
</tr>
<tr>
	<td class="label">
		<label for="maillog_sync_mapping_system">A) <?php echo $name ?></label>
	</td>
	<td class="value">
		<select lang="mul" class="select" id="maillog_sync_mapping_system">
			<option value="">--</option>
			<?php foreach ($options['system'] as $option): ?>
				<?php if (!empty($option['disabled'])): ?>
					<option value="<?php echo $option['value'] ?>" disabled="disabled">
						<?php echo !empty($option['label']) ? $option['label'].' ('.$option['value'].')' : $option['value'] ?> [<?php echo $this->__('read only') ?>]
					</option>
				<?php elseif (!empty($option['selected'])): ?>
					<option value="<?php echo $option['value'] ?>" class="has">
						<?php echo !empty($option['label']) ? $option['label'].' ('.$option['value'].')' : $option['value'] ?>
					</option>
				<?php else: ?>
					<option value="<?php echo $option['value'] ?>">
						<?php echo !empty($option['label']) ? $option['label'].' ('.$option['value'].')' : $option['value'] ?>
					</option>
				<?php endif ?>
			<?php endforeach ?>
		</select>
	</td>
	<td rowspan="2" class="scope-label" style="vertical-align:middle;">
		<button type="button" onclick="maillog.add();"><?php echo $this->__('Add') ?></button>
	</td>
	<td></td>
</tr>
<tr>
	<td class="label">
		<label for="maillog_sync_mapping_magento">B) Magento</label>
	</td>
	<td class="value">
		<select lang="mul" class="select" id="maillog_sync_mapping_magento">
			<option value="">--</option>
			<?php foreach ($options['magento'] as $option): ?>
				<?php if (!empty($option['selected'])): ?>
					<option value="<?php echo $option['value'] ?>" class="has">
						<?php echo !empty($option['label']) ? $option['label'].' ('.$option['value'].')' : $option['value'] ?>
					</option>
				<?php else: ?>
					<option value="<?php echo $option['value'] ?>">
						<?php echo !empty($option['label']) ? $option['label'].' ('.$option['value'].')' : $option['value'] ?>
					</option>
				<?php endif ?>
			<?php endforeach ?>
		</select>
	</td>
	<!-- rowspan -->
	<td></td>
</tr>